"""init

Revision ID: 762ca1de4ffc
Revises: 8b0c159c80c9
Create Date: 2017-09-20 14:35:45.523907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762ca1de4ffc'
down_revision = '8b0c159c80c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'create_at')
    # ### end Alembic commands ###
